### ISSUE TITLE
Chat submission crashes with "crypto.randomUUID is not a function" outside secure contexts

### ISSUE THREAD

**Issue by xiaoquqi** [oneprolabs/sourcelens#379]
## Summary

Sending a chat message throws:

```
Something went wrong
globalThis.crypto.randomUUID is not a function
```

Reported on `http://192.168.8.182:8000/lens/assistants/novel-assistant/chat?session=...`.

## Root cause

`frontend/src/pages/lens/chatSubmission.js` builds the idempotency key for
each run submission via `globalThis.crypto.randomUUID()`. Per spec, browsers
only expose `Crypto.randomUUID()` in secure contexts (`https://` or
`localhost`/`127.0.0.1`). Any deployment reached over plain HTTP on a
LAN IP or non-TLS domain is an insecure context, so `randomUUID` is
`undefined` there and the call throws a `TypeError`, breaking chat
submission entirely.

Introduced in 1914b40 ("Make Run history retry-aware (#207) (#212)").

## Fix

Fall back to `crypto.getRandomValues()` (not restricted to secure contexts)
to build a v4 UUID manually when `crypto.randomUUID` is unavailable.

## Repro

1. Serve the frontend over plain HTTP on a non-localhost host (e.g. a LAN
   IP such as `http://192.168.8.182:8000`).
2. Open any assistant chat and send a message.
3. The page crashes with the error above instead of submitting.
