### ISSUE TITLE
PR #96 backward-incompatible with legacy Skill.definition data: crashes assistants whose skill predates the environment-variable feature

### ISSUE THREAD

**Issue by xiaoquqi** [oneprolabs/sourcelens#116]
## Summary

Production assistant **HyperBDR-AI-Assistant** (`AI_HyperBDR`, id=1) has been completely broken since PR #96 (`feat(lens): bind Skill environment schemas per Assistant`) reached production — every single run has failed since. Confirmed via prod DB: last successful run was 2026-07-24 08:31:56 UTC; PR #96 merged 2026-07-25 06:57 UTC and was live in production (as v0.10.0+) well before the first failure at 2026-07-25 16:07:20 UTC. Every run since (including as of 2026-07-26 07:59 UTC on v0.10.3) has crashed identically.

## Root cause

```
File "/opt/backend/lens/environment_variables.py", line 212, in missing_required_environment_values
    declarations = (skill.definition or {}).get("environment") or []
AttributeError: 'str' object has no attribute 'get'
```

The Skill bound to this assistant (`AI_HyperBDR-workspace-guide`, id=2, created 2026-06-22 — over a month before PR #96) has its `definition` `JSONField` populated with a **double-encoded JSON string** (a JSON string whose *content* is itself JSON text), instead of a JSON object. This is legacy data that predates PR #96's `validate_definition` check (`backend/lens/serializers.py`), which now correctly rejects non-dict `definition` values on save — but pre-existing bad data was never caught or migrated.

`missing_required_environment_values()` assumes `skill.definition` is always a dict or `None` and has no defensive handling for this case, so it hard-crashes (`AttributeError`) instead of failing gracefully, taking down every run for any assistant bound to an affected skill.

## Blast radius

Checked all 12 skills in production via `jsonb_typeof(definition)`: **only this one skill** (id=2) has the bad `string` type; all others are proper `object`. So only `HyperBDR-AI-Assistant` is affected.

## Fix

- Immediate: corrected the bad data directly in production — re-parsed the double-encoded string back into a proper JSON object for `lens_skill.id=2`.
- Follow-up worth considering separately: `missing_required_environment_values` could defensively coerce/reject non-dict `definition` instead of crashing, so a similar data-quality issue degrades gracefully instead of hard-crashing a whole assistant. Not fixing that here since the immediate blast radius is now zero and the only known cause slipped in before PR #96's own validation existed.

**Comment by xiaoquqi** [comment]
Fixed directly in the production database — no code change needed.

## Root cause confirmed
Verified this is a genuine version-upgrade backward-incompatibility, not a pre-existing intermittent issue: this assistant's last successful run was 2026-07-24 08:31:56 UTC (before PR #96 reached production); every run since PR #96 went live (first failure 2026-07-25 16:07:20 UTC, most recently 2026-07-26 07:59:30 UTC on v0.10.3) crashed identically with the `AttributeError` described above.

## Fix
`lens_skill.id=2` (`AI_HyperBDR-workspace-guide`)'s `definition` field held a double-encoded JSON string (legacy data predating PR #96's `validate_definition` check). Re-parsed it back into a proper JSON object via the Django ORM (`Skill.objects.get(id=2)`, `definition = json.loads(old_value)`, `.save()`), preserving `content`/`description` byte-for-byte — confirmed via `jsonb_typeof` (now `object`) and by diffing the `description` field before/after.

## Verification
- `missing_required_environment(skill, None)` now returns `[]` instead of crashing.
- Ran a real end-to-end test question through the assistant on prod: it now passes dispatch validation and reaches the LLM gateway cleanly — the only remaining failure is the separate, still-ongoing upstream `DeepSeek-V4-Flash` outage (tracked informally, affects two other assistants too, unrelated to this bug). Confirms this specific crash is gone.
- Cleaned up the test session/run/message afterward.

No other skills in production have this bad data shape (checked all 12 via `jsonb_typeof(definition)`), so this was a single-record, single-assistant fix.
